// Mock data for the test user account

// Marketing events data
export const mockEvents = [
  {
    id: "evt-001",
    date: "2023-12-15",
    location: "Vino Grille",
    topic: "Retirement Outlook",
    dayOfWeek: "Friday",
    eventTime: "18:00",
    advertisingCost: "5320.52",
    foodVenueCost: "2551.50",
    typeOfMarketing: "MBI Mailer",
    topicOfMarketing: "Retirement Outlook",
    audienceDemographicsAge: "58-71",
    incomeProducingAssets: "500k-2m",
    audienceTotal: "10000",
    registrantResponses: "31",
    confirmations: "28",
    attendees: "28",
    notBooked: "24",
    nonAttendees: "0",
    firstAppointmentsFromEvent: "4",
    setAtEvent: "4",
    setAfterEvent: "0",
    totalAppointments: "4",
    firstAppointmentsAttended: "4",
    firstApptNoShows: "0",
    secondAppointmentAttended: "4",
    clientsFromEvent: "2",
    fixedAnnuityProduction: "80000",
    numAnnuitiesSold: "1",
    lifeProduction: "11000",
    numLifePoliciesSold: "0",
    numFinancialPlanningFees: "2",
    aumTotal: "490839",
    numAumClients: "2",
    status: "complete",
    roi: 274,
    conversionRate: 7.1,
    revenue: 258991,
    expenses: 7872.02,
    clients: 2,
    // New fields
    financialPlanningFees: "24000",
    marketingChannel: "Direct Mail",
    costPerLead: "253.88",
    leadQualityScore: 8.5,
    followUpEmailsSent: 12,
    followUpCallsMade: 8,
    eventSatisfactionScore: 4.7,
    speakerRating: 4.8,
    venueRating: 4.5,
    contentRelevanceScore: 4.6,
    referralsGenerated: 3,
    secondaryMarketingSource: "Email Campaign",
    geographicRegion: "Northwest",
    demographicTarget: "Retirees",
    seasonality: "Winter",
    competitorEvents: 2,
    weatherConditions: "Clear",
    marketingCreative: "Retirement Security",
    marketingMessageTesting: "A/B Test - Version A",
    eventCapacity: 40,
    eventCapacityUtilization: 70,
  },
  {
    id: "evt-002",
    date: "2023-11-30",
    location: "Parkside Hotel",
    topic: "Tax Strategies",
    dayOfWeek: "Thursday",
    eventTime: "18:30",
    advertisingCost: "4800.00",
    foodVenueCost: "2200.00",
    typeOfMarketing: "MBI Mailer",
    topicOfMarketing: "Tax Strategies",
    audienceDemographicsAge: "55-70",
    incomeProducingAssets: "400k-1.5m",
    audienceTotal: "8000",
    registrantResponses: "25",
    confirmations: "22",
    attendees: "22",
    notBooked: "19",
    nonAttendees: "0",
    firstAppointmentsFromEvent: "3",
    setAtEvent: "3",
    setAfterEvent: "0",
    totalAppointments: "3",
    firstAppointmentsAttended: "3",
    firstApptNoShows: "0",
    secondAppointmentAttended: "2",
    clientsFromEvent: "1",
    fixedAnnuityProduction: "120500",
    numAnnuitiesSold: "2",
    lifeProduction: "0",
    numLifePoliciesSold: "0",
    numFinancialPlanningFees: "0",
    aumTotal: "0",
    numAumClients: "0",
    status: "complete",
    roi: 245,
    conversionRate: 6.5,
    revenue: 210000,
    expenses: 7000,
    clients: 1,
    // New fields
    financialPlanningFees: "18000",
    marketingChannel: "Online Ads",
    costPerLead: "280.00",
    leadQualityScore: 7.9,
    followUpEmailsSent: 10,
    followUpCallsMade: 6,
    eventSatisfactionScore: 4.5,
    speakerRating: 4.6,
    venueRating: 4.3,
    contentRelevanceScore: 4.4,
    referralsGenerated: 2,
    secondaryMarketingSource: "Social Media",
    geographicRegion: "Southeast",
    demographicTarget: "Pre-Retirees",
    seasonality: "Fall",
    competitorEvents: 3,
    weatherConditions: "Rainy",
    marketingCreative: "Smart Tax Planning",
    marketingMessageTesting: "A/B Test - Version B",
    eventCapacity: 35,
    eventCapacityUtilization: 63,
  },
  {
    id: "evt-003",
    date: "2023-10-20",
    location: "Grand Conference Center",
    topic: "Estate Planning",
    dayOfWeek: "Tuesday",
    eventTime: "18:00",
    advertisingCost: "4500.00",
    foodVenueCost: "2200.00",
    typeOfMarketing: "Facebook Ads",
    topicOfMarketing: "Estate Planning",
    audienceDemographicsAge: "60-75",
    incomeProducingAssets: "750k-3m",
    audienceTotal: "7500",
    registrantResponses: "21",
    confirmations: "18",
    attendees: "21",
    notBooked: "17",
    nonAttendees: "0",
    firstAppointmentsFromEvent: "4",
    setAtEvent: "3",
    setAfterEvent: "1",
    totalAppointments: "4",
    firstAppointmentsAttended: "4",
    firstApptNoShows: "0",
    secondAppointmentAttended: "3",
    clientsFromEvent: "1",
    fixedAnnuityProduction: "150000",
    numAnnuitiesSold: "1",
    lifeProduction: "0",
    numLifePoliciesSold: "0",
    numFinancialPlanningFees: "0",
    aumTotal: "0",
    numAumClients: "0",
    status: "complete",
    roi: 198,
    conversionRate: 4.8,
    revenue: 150000,
    expenses: 6700,
    clients: 1,
    // New fields
    financialPlanningFees: "20000",
    marketingChannel: "Social Media",
    costPerLead: "310.00",
    leadQualityScore: 8.2,
    followUpEmailsSent: 9,
    followUpCallsMade: 5,
    eventSatisfactionScore: 4.3,
    speakerRating: 4.4,
    venueRating: 4.1,
    contentRelevanceScore: 4.2,
    referralsGenerated: 1,
    secondaryMarketingSource: "Referral Program",
    geographicRegion: "Midwest",
    demographicTarget: "High Net Worth Individuals",
    seasonality: "Autumn",
    competitorEvents: 1,
    weatherConditions: "Cloudy",
    marketingCreative: "Secure Your Legacy",
    marketingMessageTesting: "Control Group",
    eventCapacity: 50,
    eventCapacityUtilization: 42,
  },
  {
    id: "evt-004",
    date: "2023-09-15",
    location: "Lakeview Restaurant",
    topic: "Social Security",
    dayOfWeek: "Friday",
    eventTime: "17:30",
    advertisingCost: "5100.00",
    foodVenueCost: "2600.00",
    typeOfMarketing: "Direct Mail",
    topicOfMarketing: "Social Security",
    audienceDemographicsAge: "62-77",
    incomeProducingAssets: "600k-2.5m",
    audienceTotal: "12000",
    registrantResponses: "37",
    confirmations: "32",
    attendees: "37",
    notBooked: "30",
    nonAttendees: "0",
    firstAppointmentsFromEvent: "7",
    setAtEvent: "5",
    setAfterEvent: "2",
    totalAppointments: "7",
    firstAppointmentsAttended: "7",
    firstApptNoShows: "0",
    secondAppointmentAttended: "5",
    clientsFromEvent: "3",
    fixedAnnuityProduction: "180000",
    numAnnuitiesSold: "2",
    lifeProduction: "100000",
    numLifePoliciesSold: "1",
    numFinancialPlanningFees: "0",
    aumTotal: "0",
    numAumClients: "0",
    status: "complete",
    roi: 310,
    conversionRate: 8.1,
    revenue: 280000,
    expenses: 7700,
    clients: 3,
    // New fields
    financialPlanningFees: "22000",
    marketingChannel: "Direct Mail",
    costPerLead: "210.00",
    leadQualityScore: 8.8,
    followUpEmailsSent: 14,
    followUpCallsMade: 10,
    eventSatisfactionScore: 4.8,
    speakerRating: 4.9,
    venueRating: 4.6,
    contentRelevanceScore: 4.7,
    referralsGenerated: 4,
    secondaryMarketingSource: "Partnerships",
    geographicRegion: "Northeast",
    demographicTarget: "Seniors",
    seasonality: "Summer",
    competitorEvents: 0,
    weatherConditions: "Sunny",
    marketingCreative: "Maximize Your Benefits",
    marketingMessageTesting: "A/B Test - Version A",
    eventCapacity: 60,
    eventCapacityUtilization: 62,
  },
  {
    id: "evt-005",
    date: "2024-01-20",
    location: "Downtown Conference Hall",
    topic: "Retirement Outlook",
    dayOfWeek: "Saturday",
    eventTime: "10:00",
    advertisingCost: "6000.00",
    foodVenueCost: "3000.00",
    typeOfMarketing: "MBI Mailer",
    topicOfMarketing: "Retirement Outlook",
    audienceDemographicsAge: "60-75",
    incomeProducingAssets: "600k-3m",
    audienceTotal: "12000",
    registrantResponses: "35",
    confirmations: "30",
    attendees: "27",
    notBooked: "25",
    nonAttendees: "3",
    firstAppointmentsFromEvent: "2",
    setAtEvent: "2",
    setAfterEvent: "0",
    totalAppointments: "2",
    firstAppointmentsAttended: "2",
    firstApptNoShows: "0",
    secondAppointmentAttended: "2",
    clientsFromEvent: "2",
    fixedAnnuityProduction: "230000",
    numAnnuitiesSold: "2",
    lifeProduction: "0",
    numLifePoliciesSold: "0",
    numFinancialPlanningFees: "0",
    aumTotal: "0",
    numAumClients: "0",
    status: "complete",
    roi: 265,
    conversionRate: 7.4,
    revenue: 230000,
    expenses: 9000,
    clients: 2,
    // New fields
    financialPlanningFees: "25000",
    marketingChannel: "Direct Mail",
    costPerLead: "270.00",
    leadQualityScore: 8.3,
    followUpEmailsSent: 11,
    followUpCallsMade: 7,
    eventSatisfactionScore: 4.6,
    speakerRating: 4.7,
    venueRating: 4.4,
    contentRelevanceScore: 4.5,
    referralsGenerated: 2,
    secondaryMarketingSource: "Email Campaign",
    geographicRegion: "Southwest",
    demographicTarget: "Retirees",
    seasonality: "Winter",
    competitorEvents: 3,
    weatherConditions: "Snowy",
    marketingCreative: "Secure Your Future",
    marketingMessageTesting: "A/B Test - Version B",
    eventCapacity: 45,
    eventCapacityUtilization: 60,
  },
  {
    id: "evt-006",
    date: "2023-08-05",
    location: "Seaside Restaurant",
    topic: "Retirement Outlook",
    dayOfWeek: "Saturday",
    eventTime: "11:00",
    advertisingCost: "4800.00",
    foodVenueCost: "2700.00",
    typeOfMarketing: "Radio Ads",
    topicOfMarketing: "Retirement Outlook",
    audienceDemographicsAge: "55-70",
    incomeProducingAssets: "500k-2m",
    audienceTotal: "9000",
    registrantResponses: "26",
    confirmations: "24",
    attendees: "26",
    notBooked: "22",
    nonAttendees: "0",
    firstAppointmentsFromEvent: "4",
    setAtEvent: "3",
    setAfterEvent: "1",
    totalAppointments: "4",
    firstAppointmentsAttended: "4",
    firstApptNoShows: "0",
    secondAppointmentAttended: "3",
    clientsFromEvent: "2",
    fixedAnnuityProduction: "140000",
    numAnnuitiesSold: "1",
    lifeProduction: "0",
    numLifePoliciesSold: "0",
    numFinancialPlanningFees: "2",
    aumTotal: "100000",
    numAumClients: "1",
    status: "complete",
    roi: 285,
    conversionRate: 7.7,
    revenue: 240000,
    expenses: 7500,
    clients: 2,
    // New fields
    financialPlanningFees: "19000",
    marketingChannel: "Radio Ads",
    costPerLead: "260.00",
    leadQualityScore: 8.0,
    followUpEmailsSent: 13,
    followUpCallsMade: 9,
    eventSatisfactionScore: 4.4,
    speakerRating: 4.5,
    venueRating: 4.2,
    contentRelevanceScore: 4.3,
    referralsGenerated: 3,
    secondaryMarketingSource: "Social Media",
    geographicRegion: "West Coast",
    demographicTarget: "Pre-Retirees",
    seasonality: "Summer",
    competitorEvents: 2,
    weatherConditions: "Clear",
    marketingCreative: "Plan Your Retirement",
    marketingMessageTesting: "Control Group",
    eventCapacity: 30,
    eventCapacityUtilization: 87,
  },
  {
    id: "evt-007",
    date: "2023-07-12",
    location: "Mountain View Hotel",
    topic: "Tax Strategies",
    dayOfWeek: "Wednesday",
    eventTime: "18:00",
    advertisingCost: "4200.00",
    foodVenueCost: "2300.00",
    typeOfMarketing: "Newspaper Ads",
    topicOfMarketing: "Tax Strategies",
    audienceDemographicsAge: "50-65",
    incomeProducingAssets: "400k-1.5m",
    audienceTotal: "7000",
    registrantResponses: "18",
    confirmations: "16",
    attendees: "18",
    notBooked: "16",
    nonAttendees: "0",
    firstAppointmentsFromEvent: "2",
    setAtEvent: "1",
    setAfterEvent: "1",
    totalAppointments: "2",
    firstAppointmentsAttended: "2",
    firstApptNoShows: "0",
    secondAppointmentAttended: "1",
    clientsFromEvent: "1",
    fixedAnnuityProduction: "90000",
    numAnnuitiesSold: "1",
    lifeProduction: "0",
    numLifePoliciesSold: "0",
    numFinancialPlanningFees: "1",
    aumTotal: "100000",
    numAumClients: "1",
    status: "complete",
    roi: 225,
    conversionRate: 5.5,
    revenue: 190000,
    expenses: 6500,
    clients: 1,
    // New fields
    financialPlanningFees: "17000",
    marketingChannel: "Newspaper Ads",
    costPerLead: "290.00",
    leadQualityScore: 7.7,
    followUpEmailsSent: 8,
    followUpCallsMade: 4,
    eventSatisfactionScore: 4.2,
    speakerRating: 4.3,
    venueRating: 4.0,
    contentRelevanceScore: 4.1,
    referralsGenerated: 0,
    secondaryMarketingSource: "None",
    geographicRegion: "Mountain States",
    demographicTarget: "Affluent Individuals",
    seasonality: "Spring",
    competitorEvents: 1,
    weatherConditions: "Mild",
    marketingCreative: "Reduce Your Tax Burden",
    marketingMessageTesting: "A/B Test - Version A",
    eventCapacity: 40,
    eventCapacityUtilization: 45,
  },
  {
    id: "evt-008",
    date: "2023-06-28",
    location: "Riverside Conference Center",
    topic: "Estate Planning",
    dayOfWeek: "Thursday",
    eventTime: "17:30",
    advertisingCost: "4500.00",
    foodVenueCost: "2500.00",
    typeOfMarketing: "Email Campaign",
    topicOfMarketing: "Estate Planning",
    audienceDemographicsAge: "60-75",
    incomeProducingAssets: "750k-3m",
    audienceTotal: "15000",
    registrantResponses: "29",
    confirmations: "26",
    attendees: "29",
    notBooked: "25",
    nonAttendees: "0",
    firstAppointmentsFromEvent: "4",
    setAtEvent: "3",
    setAfterEvent: "1",
    totalAppointments: "4",
    firstAppointmentsAttended: "4",
    firstApptNoShows: "0",
    secondAppointmentAttended: "3",
    clientsFromEvent: "2",
    fixedAnnuityProduction: "120000",
    numAnnuitiesSold: "1",
    lifeProduction: "0",
    numLifePoliciesSold: "0",
    numFinancialPlanningFees: "2",
    aumTotal: "100000",
    numAumClients: "1",
    status: "complete",
    roi: 250,
    conversionRate: 6.8,
    revenue: 220000,
    expenses: 7000,
    clients: 2,
    // New fields
    financialPlanningFees: "18000",
    marketingChannel: "Email Campaign",
    costPerLead: "240.00",
    leadQualityScore: 8.4,
    followUpEmailsSent: 10,
    followUpCallsMade: 6,
    eventSatisfactionScore: 4.7,
    speakerRating: 4.8,
    venueRating: 4.5,
    contentRelevanceScore: 4.6,
    referralsGenerated: 3,
    secondaryMarketingSource: "Referral Program",
    geographicRegion: "Pacific Northwest",
    demographicTarget: "High Net Worth Individuals",
    seasonality: "Spring",
    competitorEvents: 0,
    weatherConditions: "Sunny",
    marketingCreative: "Protect Your Assets",
    marketingMessageTesting: "A/B Test - Version B",
    eventCapacity: 55,
    eventCapacityUtilization: 53,
  },
  {
    id: "evt-009",
    date: "2023-05-17",
    location: "City Center Venue",
    topic: "Social Security",
    dayOfWeek: "Wednesday",
    eventTime: "18:00",
    advertisingCost: "5320.52",
    foodVenueCost: "2551.50",
    typeOfMarketing: "MBI Mailer",
    topicOfMarketing: "Social Security",
    audienceDemographicsAge: "58-71",
    incomeProducingAssets: "500k-2m",
    audienceTotal: "10000",
    registrantResponses: "31",
    confirmations: "28",
    attendees: "28",
    notBooked: "24",
    nonAttendees: "0",
    firstAppointmentsFromEvent: "4",
    setAtEvent: "4",
    setAfterEvent: "0",
    totalAppointments: "4",
    firstAppointmentsAttended: "4",
    firstApptNoShows: "0",
    secondAppointmentAttended: "4",
    clientsFromEvent: "2",
    fixedAnnuityProduction: "80000",
    numAnnuitiesSold: "1",
    lifeProduction: "11000",
    numLifePoliciesSold: "0",
    numFinancialPlanningFees: "2",
    aumTotal: "167991",
    numAumClients: "2",
    status: "complete",
    roi: 274,
    conversionRate: 7.1,
    revenue: 258991,
    expenses: 7872.02,
    clients: 2,
    // New fields
    financialPlanningFees: "21000",
    marketingChannel: "Direct Mail",
    costPerLead: "250.00",
    leadQualityScore: 8.6,
    followUpEmailsSent: 12,
    followUpCallsMade: 8,
    eventSatisfactionScore: 4.5,
    speakerRating: 4.6,
    venueRating: 4.3,
    contentRelevanceScore: 4.4,
    referralsGenerated: 3,
    secondaryMarketingSource: "Partnerships",
    geographicRegion: "Southeast",
    demographicTarget: "Retirees",
    seasonality: "Spring",
    competitorEvents: 1,
    weatherConditions: "Rainy",
    marketingCreative: "Understand Social Security",
    marketingMessageTesting: "Control Group",
    eventCapacity: 35,
    eventCapacityUtilization: 80,
  },
]

// Test user credentials
export const TEST_USER = {
  email: "test@example.com",
  password: "password123",
  name: "Test User",
  hasData: true,
}
